/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project1;

public class App {
  public static void main(String[] args) {
    System.out.println("**대학교 학점 관리 시스템");
    System.out.println("----------------------------------");

    System.out.print("학번: ");
    System.out.println(1001);

    System.out.printf("이름: %s\n", "홍길동");

    System.out.printf("C언어: %s\n", "A+");

    System.out.printf("C++: %s\n", "A+");

    System.out.printf("자바: %s\n", "A+");

    System.out.printf("리눅스: %s\n", "A+");

    System.out.printf("학점: %f\n", 4.5);

    System.out.printf("장학금: %b\n", true);
  }
}
